### ISSUE TITLE
Extension to enforce HTTPS

### ISSUE THREAD

**Issue by jperichon** [codeamp/circuit#244]
For a few projects, we would like to be able to enforce usage of HTTPS while improving usability and redirect http -> https.

Is that doable currently? If not, what's your thoughts on this feature.

**Comment by amoskyler** [comment]
@jperichon this is a good feature - However, it's not exactly possible with our current implementation as far as I understand it.

ELBs don't offer automatic HTTPS upgrading - when a non HTTPS request is made to an HTTPS ELB endpoint, the ELB hangs on the request. The request is never proxied back to a backend web service, which is the appropriate place to add the upgrade.

https://aws.amazon.com/premiumsupport/knowledge-center/redirect-http-https-elb/

One possible way to solve this is add an HTTP web server on 80 which simply redirects requests to HTTPS on 443 for every HTTPS service added. It may be easier to implement this once Istio is rolled out.

**Comment by amoskyler** [comment]
I suppose it may also work to simply create a service which runs an nginx instance that performs redirects (the service is exposed on port 80)

**Comment by aballman** [comment]
Another reference:
https://oanhnn.github.io/2016-02-29/how-to-force-https-behind-aws-elb.html

**Comment by sasso** [comment]
I don't think this should be solved in CodeAmp. HTTPS should be enforced with HSTS (https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet). You could introduce this on the ingress but this is on a lower lever CodeAmp should handle.
