### ISSUE TITLE
Support arrays as Env variables

### ISSUE THREAD

**Issue by mellauyellow** [codeamp/circuit#246]
Any way we can support arrays as a data type for Env variables?

**Comment by amoskyler** [comment]
@mellauyellow can you explain a bit more about your use case/what you imagine the functionality will do?

**Comment by amoskyler** [comment]
For context, environment variables are handled in a few ways in codeamp.
The `File` type writes a file to `/etc/secrets/<secret_key>`.

`Build Arg` is a KEY:VALUE pair which is passed into the docker builder context during deploy.

And finally `env` is a KEY:VALUE pair which is passed into a container on start. This is identical to starting a docker container with a `--env SOME_ENV_VAR=envarvalue`. It's also very similar to calling `export SOME_ENV_VAR=envvarvalue` within a shell context.

**Comment by aballman** [comment]
I think @amoskyler talked to you offline maybe.
We can't really do much other than point you towards a SO article describing how to do what you want in shell. https://stackoverflow.com/questions/27702452/loop-through-a-comma-separated-shell-variable
