### ISSUE TITLE
Incremental Service Release

### ISSUE THREAD

**Issue by jaahay** [codeamp/circuit#247]
Please enable release control at the service level. Assuming there is no change in the deployed image/binary, it is still possible that we would want to re-release the same service. This will enable scaling, secret- and environment-configuration of a single service.

**Comment by amoskyler** [comment]
There may be room for this in the future. Within the current system there is no way to implement it without refactoring large parts of code and re-designing how we think about the relationship between deploys and projects. This is something we will keep our eyes on as we iterate on codeamp.
