### ISSUE TITLE
Report Error if Deployment Name Exceeds Kubernetes Limit

### ISSUE THREAD

**Issue by aballman** [codeamp/circuit#324]
**Describe the bug**
Report an error if a provided project / service name exceeds the Kubernetes service limit.
We'll need to have some sort of hard limit on service names anyways as creating a project and deploying to Kubernetes are entirely decoupled.

```Message: Error creating deployment: Deployment.apps "checkr-providers-national-student-education-verification-request-handler" is invalid: [metadata.labels: Invalid value: "checkr-providers-national-student-education-verification-request-handler": must be no more than 63 characters, spec.selector.matchLabels: Invalid value: "checkr-providers-national-student-education-verification-request-handler": must be no more than 63 characters, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"checkr-providers-national-student-education-verification-request-handler"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: invalid label selector.]```

**Comment by drshrey** [comment]
I may have duped this here: https://github.com/codeamp/circuit/issues/327 although we're not doing validation for project names, so I could use this issue as a way of addressing that (and potentially any other string limitations with Kubernetes).

**Comment by aballman** [comment]
Might as well add in extra validation at consumption time as well. It's a quick sanity check. Maybe someone edits the DB directly and bypasses validation. "Hey! It could happen!" - 1990s McDonalds

**Comment by aballman** [comment]
Closing this as it looks like it is resolved in panel and circuit.
