### ISSUE TITLE
Persist artifacts and state messages on failed extension events

### ISSUE THREAD

**Issue by drshrey** [codeamp/circuit#65]
When i install load balancer, i get the elbdns back but there is a failure in route 53 connecting a dns with the elb. However, i get no error message and the previous artifacts with the elbdns are erased.

**Comment by amoskyler** [comment]
The issue here is we are showing Artifacts but not status messages/state messages for the latest events. So, when route53 extension fails, it doesn't send any artifacts, however it does send a failed status with a state message.

**Comment by drshrey** [comment]
We shouldn't then simply replace Artifacts when handling status events since this introduces possible regressions for Artifact data. Rather, we should add into the existing structure in codeamp.go. We should definitely address the state message display issue in panel, but there shouldn't be any regression on Artifacts data upon failure.

**Comment by amoskyler** [comment]
Are extensions meant to have specifically one set of artifacts? Or are they supposed to collect all artifacts generated even between internal extension calls?

**Comment by drshrey** [comment]
An extension is tied to *one set of Artifacts*. In this case, we are sending two different extension type events with the same Extension Id. In order to handle the case of different extension type events contributing to the same extension, we should change our current method of Artifacts replacement to Artifacts mutability (for now, just adding/ overriding existing keys).
